name: Task 2 Workflow

on:
  push:
    branches: [main]

jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - name: Check system information
        run: uname -a

      - name: Check disk space
        run: df -h

      - name: Check memory usage
        run: free -h
      - name: Check network configuration
        run: ifconfig -a
      - name: Check system uptime
        run: uptime
      - name: Check logged in users
        run: who
      - name: check python version
        run: python --version 
      - name: Check docker version
        run: docker --version
