name : Package Workflow System Information


on:
  push:
    branches: [main]

jobs:
  Packages_commands:
    runs-on: ubuntu-latest
    steps:
      - name: upgrading Linux packages
        run: sudo apt update && sudo apt upgrade -y
      - name: installing curl
        run: sudo apt install curl -y
      - name: Installation of nginx
        run: sudo apt install nginx -y
      - name: starting nginx service
        run: sudo systemctl start nginx
      - name: checking nginx status
        run: sudo systemctl status nginx
      - name: sudo enable nginx to start on boot
        run: sudo systemctl enable nginx
    
