name : uptime-kuma  

on:
  push:

    branches: [main]

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Change Directory
        run: cd /opt
      - name: Create Directory
        run: sudo mkdir uptime-kuma
      - name: Change Directory
        run: cd uptime-kuma
      - name: Clone the repository
        run: curl -o compose.yaml https://raw.githubusercontent.com/louislam/uptime-kuma/master/compose.yaml

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installation Of Docker Compose  
        run: sudo apt install docker-compose -y
      - name: Docker Compose Build
        run: sudo docker-compose build -d
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker Running Container
        run: sudo docker ps -a
